;
; File generated by cc65 v 2.17 - Git 644d623d
;
	.fopt		compiler,"cc65 v 2.17 - Git 644d623d"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_pal_col
	.import		_pal_bright
	.import		_ppu_wait_frame
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_ppu_on_bg
	.import		_oam_clear
	.import		_oam_meta_spr
	.import		_music_play
	.import		_music_stop
	.import		_music_pause
	.import		_sfx_play
	.import		_pad_trigger
	.import		_pad_state
	.import		_scroll
	.import		_bank_spr
	.import		_bank_bg
	.import		_rand8
	.import		_set_vram_update
	.import		_vram_adr
	.import		_vram_put
	.import		_vram_fill
	.import		_vram_read
	.import		_vram_write
	.import		_vram_unrle
	.import		_memcpy
	.import		_delay
	.export		_title_nam
	.export		_level_nam
	.export		_gameover_nam
	.export		_welldone_nam
	.export		_level1_nam
	.export		_level2_nam
	.export		_level3_nam
	.export		_level4_nam
	.export		_level5_nam
	.export		_palTitle
	.export		_palGame1
	.export		_palGame2
	.export		_palGame3
	.export		_palGame4
	.export		_palGame5
	.export		_palGameSpr
	.export		_sprPlayer
	.export		_sprEnemy1
	.export		_sprEnemy2
	.export		_sprEnemy3
	.export		_sprListPlayer
	.export		_levelList
	.export		_updateListData
	.export		_statsStr
	.export		_screenList
	.export		_screenMusicList
	.export		_largeNums
	.export		_pal_fade_to
	.export		_title_screen
	.export		_show_screen
	.export		_player_move
	.export		_put_num
	.export		_game_loop
	.export		_main

.segment	"DATA"

_screenList:
	.addr	_level_nam
	.addr	_gameover_nam
	.addr	_welldone_nam
.segment	"ZEROPAGE"

.segment	"RODATA"

_title_nam:
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$85
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$05
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$07
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$05
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$05
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$05
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$05
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$05
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$05
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$AA
	.byte	$30
	.byte	$32
	.byte	$25
	.byte	$33
	.byte	$33
	.byte	$00
	.byte	$00
	.byte	$33
	.byte	$34
	.byte	$21
	.byte	$32
	.byte	$34
	.byte	$00
	.byte	$01
	.byte	$93
	.byte	$30
	.byte	$24
	.byte	$12
	.byte	$10
	.byte	$11
	.byte	$12
	.byte	$00
	.byte	$33
	.byte	$28
	.byte	$29
	.byte	$32
	.byte	$35
	.byte	$00
	.byte	$01
	.byte	$8A
	.byte	$55
	.byte	$01
	.byte	$08
	.byte	$99
	.byte	$AA
	.byte	$FF
	.byte	$BB
	.byte	$AA
	.byte	$55
	.byte	$01
	.byte	$02
	.byte	$99
	.byte	$AA
	.byte	$FF
	.byte	$BB
	.byte	$AA
	.byte	$55
	.byte	$01
	.byte	$02
	.byte	$99
	.byte	$AA
	.byte	$FF
	.byte	$BB
	.byte	$AA
	.byte	$55
	.byte	$55
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$AA
	.byte	$01
	.byte	$07
	.byte	$0A
	.byte	$01
	.byte	$07
	.byte	$01
	.byte	$00
_level_nam:
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$FE
	.byte	$00
	.byte	$01
	.byte	$89
	.byte	$67
	.byte	$00
	.byte	$65
	.byte	$66
	.byte	$67
	.byte	$68
	.byte	$65
	.byte	$66
	.byte	$67
	.byte	$00
	.byte	$01
	.byte	$16
	.byte	$67
	.byte	$00
	.byte	$65
	.byte	$6D
	.byte	$67
	.byte	$68
	.byte	$65
	.byte	$6D
	.byte	$67
	.byte	$00
	.byte	$01
	.byte	$16
	.byte	$72
	.byte	$78
	.byte	$72
	.byte	$73
	.byte	$75
	.byte	$76
	.byte	$72
	.byte	$73
	.byte	$72
	.byte	$78
	.byte	$00
	.byte	$01
	.byte	$FE
	.byte	$00
	.byte	$01
	.byte	$FE
	.byte	$00
	.byte	$01
	.byte	$2E
	.byte	$01
	.byte	$00
_gameover_nam:
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$FE
	.byte	$00
	.byte	$01
	.byte	$86
	.byte	$60
	.byte	$61
	.byte	$60
	.byte	$62
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$66
	.byte	$00
	.byte	$60
	.byte	$62
	.byte	$67
	.byte	$68
	.byte	$65
	.byte	$66
	.byte	$65
	.byte	$62
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$01
	.byte	$0C
	.byte	$67
	.byte	$6A
	.byte	$67
	.byte	$68
	.byte	$6B
	.byte	$6C
	.byte	$65
	.byte	$6D
	.byte	$00
	.byte	$67
	.byte	$68
	.byte	$67
	.byte	$68
	.byte	$65
	.byte	$6D
	.byte	$67
	.byte	$6E
	.byte	$00
	.byte	$98
	.byte	$00
	.byte	$01
	.byte	$0C
	.byte	$6F
	.byte	$70
	.byte	$65
	.byte	$71
	.byte	$67
	.byte	$68
	.byte	$72
	.byte	$73
	.byte	$00
	.byte	$6F
	.byte	$74
	.byte	$75
	.byte	$76
	.byte	$72
	.byte	$73
	.byte	$65
	.byte	$77
	.byte	$00
	.byte	$99
	.byte	$00
	.byte	$01
	.byte	$FE
	.byte	$00
	.byte	$01
	.byte	$FE
	.byte	$00
	.byte	$01
	.byte	$28
	.byte	$01
	.byte	$00
_welldone_nam:
	.byte	$02
	.byte	$00
	.byte	$02
	.byte	$FE
	.byte	$00
	.byte	$02
	.byte	$86
	.byte	$67
	.byte	$68
	.byte	$65
	.byte	$66
	.byte	$67
	.byte	$00
	.byte	$67
	.byte	$00
	.byte	$00
	.byte	$65
	.byte	$62
	.byte	$60
	.byte	$62
	.byte	$63
	.byte	$79
	.byte	$65
	.byte	$66
	.byte	$00
	.byte	$97
	.byte	$00
	.byte	$02
	.byte	$0C
	.byte	$82
	.byte	$83
	.byte	$65
	.byte	$6D
	.byte	$67
	.byte	$00
	.byte	$67
	.byte	$00
	.byte	$00
	.byte	$67
	.byte	$68
	.byte	$67
	.byte	$68
	.byte	$84
	.byte	$85
	.byte	$65
	.byte	$6D
	.byte	$00
	.byte	$98
	.byte	$00
	.byte	$02
	.byte	$0C
	.byte	$8E
	.byte	$8F
	.byte	$72
	.byte	$73
	.byte	$72
	.byte	$78
	.byte	$72
	.byte	$78
	.byte	$00
	.byte	$72
	.byte	$74
	.byte	$6F
	.byte	$74
	.byte	$67
	.byte	$68
	.byte	$72
	.byte	$73
	.byte	$00
	.byte	$99
	.byte	$00
	.byte	$02
	.byte	$2C
	.byte	$21
	.byte	$2C
	.byte	$2C
	.byte	$00
	.byte	$27
	.byte	$25
	.byte	$2D
	.byte	$33
	.byte	$00
	.byte	$23
	.byte	$2F
	.byte	$2C
	.byte	$2C
	.byte	$25
	.byte	$23
	.byte	$34
	.byte	$25
	.byte	$24
	.byte	$01
	.byte	$00
	.byte	$02
	.byte	$FE
	.byte	$00
	.byte	$02
	.byte	$C7
	.byte	$55
	.byte	$02
	.byte	$17
	.byte	$00
	.byte	$02
	.byte	$07
	.byte	$02
	.byte	$00
_level1_nam:
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$FE
	.byte	$00
	.byte	$01
	.byte	$08
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$40
	.byte	$41
	.byte	$10
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$42
	.byte	$43
	.byte	$44
	.byte	$44
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$11
	.byte	$44
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$44
	.byte	$44
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0F
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$FE
	.byte	$00
	.byte	$01
	.byte	$1A
	.byte	$BD
	.byte	$AD
	.byte	$AD
	.byte	$6D
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$B9
	.byte	$AD
	.byte	$AD
	.byte	$6E
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$B9
	.byte	$AD
	.byte	$AD
	.byte	$6E
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$0D
	.byte	$01
	.byte	$03
	.byte	$00
	.byte	$01
	.byte	$11
	.byte	$01
	.byte	$00
_level2_nam:
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$C5
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$40
	.byte	$41
	.byte	$10
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$11
	.byte	$44
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$44
	.byte	$44
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$44
	.byte	$44
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$40
	.byte	$41
	.byte	$12
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$44
	.byte	$44
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$CE
	.byte	$40
	.byte	$70
	.byte	$01
	.byte	$03
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$4C
	.byte	$6A
	.byte	$BA
	.byte	$B9
	.byte	$BA
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$4C
	.byte	$7A
	.byte	$6A
	.byte	$01
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$4C
	.byte	$6A
	.byte	$01
	.byte	$02
	.byte	$BA
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$4C
	.byte	$7A
	.byte	$01
	.byte	$03
	.byte	$31
	.byte	$00
	.byte	$01
	.byte	$10
	.byte	$01
	.byte	$00
_level3_nam:
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$C5
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$40
	.byte	$41
	.byte	$10
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$11
	.byte	$44
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$44
	.byte	$44
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$44
	.byte	$44
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$07
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$07
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$12
	.byte	$44
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$44
	.byte	$44
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$CE
	.byte	$40
	.byte	$70
	.byte	$01
	.byte	$03
	.byte	$30
	.byte	$00
	.byte	$40
	.byte	$7C
	.byte	$6A
	.byte	$BA
	.byte	$B9
	.byte	$BA
	.byte	$71
	.byte	$30
	.byte	$4C
	.byte	$6A
	.byte	$01
	.byte	$02
	.byte	$BA
	.byte	$B9
	.byte	$BA
	.byte	$31
	.byte	$4C
	.byte	$7A
	.byte	$6E
	.byte	$6A
	.byte	$6A
	.byte	$BA
	.byte	$7A
	.byte	$31
	.byte	$00
	.byte	$4C
	.byte	$7A
	.byte	$7E
	.byte	$7A
	.byte	$7A
	.byte	$31
	.byte	$00
	.byte	$01
	.byte	$10
	.byte	$01
	.byte	$00
_level4_nam:
	.byte	$02
	.byte	$00
	.byte	$02
	.byte	$85
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$02
	.byte	$13
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$02
	.byte	$13
	.byte	$40
	.byte	$41
	.byte	$10
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$02
	.byte	$07
	.byte	$42
	.byte	$43
	.byte	$44
	.byte	$44
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$02
	.byte	$07
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$11
	.byte	$44
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$02
	.byte	$07
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$44
	.byte	$44
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$12
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$02
	.byte	$07
	.byte	$42
	.byte	$43
	.byte	$44
	.byte	$44
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$02
	.byte	$07
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$13
	.byte	$44
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$02
	.byte	$07
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$44
	.byte	$44
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$02
	.byte	$13
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$02
	.byte	$13
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$02
	.byte	$8E
	.byte	$4C
	.byte	$AD
	.byte	$AD
	.byte	$71
	.byte	$70
	.byte	$70
	.byte	$30
	.byte	$40
	.byte	$7C
	.byte	$6E
	.byte	$B9
	.byte	$B9
	.byte	$BA
	.byte	$BA
	.byte	$31
	.byte	$4C
	.byte	$6A
	.byte	$02
	.byte	$02
	.byte	$BA
	.byte	$BA
	.byte	$B9
	.byte	$31
	.byte	$4C
	.byte	$6E
	.byte	$6A
	.byte	$02
	.byte	$02
	.byte	$BA
	.byte	$7A
	.byte	$31
	.byte	$4C
	.byte	$7A
	.byte	$7A
	.byte	$7E
	.byte	$AE
	.byte	$A9
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$0C
	.byte	$0D
	.byte	$0D
	.byte	$01
	.byte	$00
	.byte	$02
	.byte	$08
	.byte	$02
	.byte	$00
_level5_nam:
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$83
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$07
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$07
	.byte	$40
	.byte	$41
	.byte	$10
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$11
	.byte	$44
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$07
	.byte	$42
	.byte	$43
	.byte	$44
	.byte	$44
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$44
	.byte	$44
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$45
	.byte	$46
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$47
	.byte	$48
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$40
	.byte	$41
	.byte	$12
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$45
	.byte	$46
	.byte	$13
	.byte	$44
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$07
	.byte	$42
	.byte	$43
	.byte	$44
	.byte	$44
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$47
	.byte	$48
	.byte	$44
	.byte	$44
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$07
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$40
	.byte	$41
	.byte	$00
	.byte	$01
	.byte	$07
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$42
	.byte	$43
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$BD
	.byte	$BD
	.byte	$AD
	.byte	$01
	.byte	$03
	.byte	$6D
	.byte	$6D
	.byte	$BD
	.byte	$A9
	.byte	$AD
	.byte	$AE
	.byte	$A9
	.byte	$AD
	.byte	$AE
	.byte	$6D
	.byte	$BD
	.byte	$AE
	.byte	$AE
	.byte	$BD
	.byte	$AE
	.byte	$01
	.byte	$02
	.byte	$6E
	.byte	$B9
	.byte	$AD
	.byte	$A9
	.byte	$A9
	.byte	$B9
	.byte	$AD
	.byte	$A9
	.byte	$6D
	.byte	$BD
	.byte	$AE
	.byte	$01
	.byte	$02
	.byte	$AD
	.byte	$AE
	.byte	$AE
	.byte	$6E
	.byte	$BD
	.byte	$B9
	.byte	$AD
	.byte	$AE
	.byte	$A9
	.byte	$AD
	.byte	$6E
	.byte	$6D
	.byte	$0D
	.byte	$01
	.byte	$07
	.byte	$01
	.byte	$00
_palTitle:
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$1C
	.byte	$2C
	.byte	$3C
	.byte	$0F
	.byte	$12
	.byte	$22
	.byte	$32
	.byte	$0F
	.byte	$14
	.byte	$24
	.byte	$34
_palGame1:
	.byte	$0F
	.byte	$11
	.byte	$32
	.byte	$30
	.byte	$0F
	.byte	$1C
	.byte	$2C
	.byte	$3C
	.byte	$0F
	.byte	$09
	.byte	$27
	.byte	$38
	.byte	$0F
	.byte	$11
	.byte	$21
	.byte	$31
_palGame2:
	.byte	$0F
	.byte	$11
	.byte	$32
	.byte	$30
	.byte	$0F
	.byte	$11
	.byte	$21
	.byte	$31
	.byte	$0F
	.byte	$07
	.byte	$27
	.byte	$38
	.byte	$0F
	.byte	$13
	.byte	$23
	.byte	$33
_palGame3:
	.byte	$0F
	.byte	$11
	.byte	$32
	.byte	$30
	.byte	$0F
	.byte	$15
	.byte	$25
	.byte	$35
	.byte	$0F
	.byte	$05
	.byte	$27
	.byte	$38
	.byte	$0F
	.byte	$13
	.byte	$23
	.byte	$33
_palGame4:
	.byte	$0F
	.byte	$11
	.byte	$32
	.byte	$30
	.byte	$0F
	.byte	$19
	.byte	$29
	.byte	$39
	.byte	$0F
	.byte	$0B
	.byte	$27
	.byte	$38
	.byte	$0F
	.byte	$17
	.byte	$27
	.byte	$37
_palGame5:
	.byte	$0F
	.byte	$11
	.byte	$32
	.byte	$30
	.byte	$0F
	.byte	$16
	.byte	$26
	.byte	$36
	.byte	$0F
	.byte	$07
	.byte	$27
	.byte	$38
	.byte	$0F
	.byte	$18
	.byte	$28
	.byte	$38
_palGameSpr:
	.byte	$0F
	.byte	$0F
	.byte	$29
	.byte	$30
	.byte	$0F
	.byte	$0F
	.byte	$26
	.byte	$30
	.byte	$0F
	.byte	$0F
	.byte	$24
	.byte	$30
	.byte	$0F
	.byte	$0F
	.byte	$21
	.byte	$30
_sprPlayer:
	.byte	$00
	.byte	$FF
	.byte	$49
	.byte	$00
	.byte	$08
	.byte	$FF
	.byte	$4A
	.byte	$00
	.byte	$00
	.byte	$07
	.byte	$4B
	.byte	$00
	.byte	$08
	.byte	$07
	.byte	$4C
	.byte	$00
	.byte	$80
_sprEnemy1:
	.byte	$00
	.byte	$FF
	.byte	$4D
	.byte	$01
	.byte	$08
	.byte	$FF
	.byte	$4E
	.byte	$01
	.byte	$00
	.byte	$07
	.byte	$4F
	.byte	$01
	.byte	$08
	.byte	$07
	.byte	$50
	.byte	$01
	.byte	$80
_sprEnemy2:
	.byte	$00
	.byte	$FF
	.byte	$4D
	.byte	$02
	.byte	$08
	.byte	$FF
	.byte	$4E
	.byte	$02
	.byte	$00
	.byte	$07
	.byte	$4F
	.byte	$02
	.byte	$08
	.byte	$07
	.byte	$50
	.byte	$02
	.byte	$80
_sprEnemy3:
	.byte	$00
	.byte	$FF
	.byte	$4D
	.byte	$03
	.byte	$08
	.byte	$FF
	.byte	$4E
	.byte	$03
	.byte	$00
	.byte	$07
	.byte	$4F
	.byte	$03
	.byte	$08
	.byte	$07
	.byte	$50
	.byte	$03
	.byte	$80
_sprListPlayer:
	.addr	_sprPlayer
	.addr	_sprEnemy1
	.addr	_sprEnemy2
	.addr	_sprEnemy3
_levelList:
	.addr	_level1_nam
	.addr	_palGame1
	.addr	_level2_nam
	.addr	_palGame2
	.addr	_level3_nam
	.addr	_palGame3
	.addr	_level4_nam
	.addr	_palGame3
	.addr	_level5_nam
	.addr	_palGame3
_updateListData:
	.byte	$28
	.byte	$00
	.byte	$44
	.byte	$28
	.byte	$00
	.byte	$44
	.byte	$28
	.byte	$00
	.byte	$44
	.byte	$28
	.byte	$00
	.byte	$44
	.byte	$20
	.byte	$4F
	.byte	$10
	.byte	$20
	.byte	$50
	.byte	$10
	.byte	$20
	.byte	$51
	.byte	$10
	.byte	$FF
_statsStr:
	.byte	$2C
	.byte	$25
	.byte	$36
	.byte	$25
	.byte	$2C
	.byte	$1A
	.byte	$00
	.byte	$00
	.byte	$27
	.byte	$25
	.byte	$2D
	.byte	$33
	.byte	$1A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0F
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$2C
	.byte	$29
	.byte	$36
	.byte	$25
	.byte	$33
	.byte	$1A
_screenMusicList:
	.byte	$00
	.byte	$03
	.byte	$04
_largeNums:
	.byte	$7A
	.byte	$7B
	.byte	$7C
	.byte	$7D
	.byte	$7C
	.byte	$7D
	.byte	$7E
	.byte	$7F
	.byte	$80
	.byte	$81
	.byte	$86
	.byte	$7B
	.byte	$87
	.byte	$88
	.byte	$89
	.byte	$8A
	.byte	$8B
	.byte	$8C
	.byte	$8D
	.byte	$7D
	.byte	$90
	.byte	$91
	.byte	$92
	.byte	$93
	.byte	$94
	.byte	$95
	.byte	$96
	.byte	$7F
	.byte	$94
	.byte	$95

.segment	"BSS"

_map:
	.res	208,$00
.segment	"ZEROPAGE"
_i:
	.res	1,$00
_j:
	.res	1,$00
_ptr:
	.res	1,$00
_spr:
	.res	1,$00
_px:
	.res	1,$00
_py:
	.res	1,$00
_wait:
	.res	1,$00
_i16:
	.res	2,$00
_iy:
	.res	2,$00
_dy:
	.res	2,$00
_dir:
	.res	4,$00
_nameRow:
	.res	32,$00
_player_all:
	.res	1,$00
_player_x:
	.res	8,$00
_player_y:
	.res	8,$00
_player_dir:
	.res	4,$00
_player_cnt:
	.res	8,$00
_player_speed:
	.res	8,$00
_player_wait:
	.res	4,$00
_items_count:
	.res	1,$00
_items_collected:
	.res	1,$00
_game_level:
	.res	1,$00
_game_lives:
	.res	1,$00
_game_done:
	.res	1,$00
_game_paused:
	.res	1,$00
_game_clear:
	.res	1,$00
_frame_cnt:
	.res	1,$00
_bright:
	.res	1,$00
_update_list:
	.res	22,$00

; ---------------------------------------------------------------
; void __near__ pal_fade_to (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_pal_fade_to: near

.segment	"CODE"

	jsr     pushax
	ldy     #$01
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L0E95
	jsr     _music_stop
	jmp     L0E95
L0E93:	lda     #$04
	jsr     _delay
	ldx     #$00
	lda     _bright
	ldy     #$00
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcs     L1224
	inc     _bright
	jmp     L1223
L1224:	dec     _bright
L1223:	lda     _bright
	jsr     _pal_bright
L0E95:	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cpx     #$00
	bne     L0E93
	cmp     _bright
	bne     L0E93
	lda     _bright
	bne     L0EA0
	jsr     _ppu_off
	ldx     #$00
	txa
	jsr     _set_vram_update
	jsr     push0
	jsr     _scroll
L0EA0:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ title_screen (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_title_screen: near

.segment	"CODE"

	ldx     #$FF
	lda     #$F8
	jsr     pushax
	inx
	lda     #$F0
	jsr     _scroll
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
	lda     #<(_title_nam)
	ldx     #>(_title_nam)
	jsr     _vram_unrle
	ldx     #$28
	lda     #$00
	jsr     _vram_adr
	lda     #$00
	jsr     pusha
	ldx     #$04
	jsr     _vram_fill
	lda     #<(_palTitle)
	ldx     #>(_palTitle)
	jsr     _pal_bg
	lda     #$04
	jsr     _pal_bright
	jsr     _ppu_on_bg
	lda     #$14
	jsr     _delay
	ldx     #$0F
	lda     #$00
	sta     _iy
	stx     _iy+1
	ldx     #$FF
	lda     #$80
	sta     _dy
	stx     _dy+1
	lda     #$00
	sta     _frame_cnt
	lda     #$A0
	sta     _wait
	lda     #$04
	sta     _bright
L0EC6:	jsr     _ppu_wait_frame
	ldx     #$FF
	lda     #$F8
	jsr     pushax
	lda     _iy
	ldx     _iy+1
	jsr     asrax4
	jsr     _scroll
	lda     #$00
	jsr     _pad_trigger
	and     #$10
	bne     L0EC7
	lda     _dy
	clc
	adc     _iy
	sta     _iy
	lda     _dy+1
	adc     _iy+1
	sta     _iy+1
	ldx     _iy+1
	cpx     #$80
	bcc     L0ED3
	lda     #$00
	sta     _iy
	sta     _iy+1
	lda     _dy
	ldx     _dy+1
	jsr     negax
	jsr     asrax1
	sta     _dy
	stx     _dy+1
L0ED3:	lda     _dy
	cmp     #$81
	lda     _dy+1
	sbc     #$FF
	bvs     L0EDC
	eor     #$80
L0EDC:	bpl     L0ED9
	lda     _dy
	sec
	sbc     #$02
	sta     _dy
	bcs     L0ED9
	dec     _dy+1
L0ED9:	lda     _wait
	beq     L0EE0
	dec     _wait
	jmp     L0EC6
L0EE0:	lda     #$02
	jsr     pusha
	lda     _frame_cnt
	and     #$20
	beq     L1225
	lda     #$0F
	jmp     L1226
L1225:	lda     #$20
L1226:	jsr     _pal_col
	inc     _frame_cnt
	jmp     L0EC6
L0EC7:	ldx     #$FF
	lda     #$F8
	jsr     pushax
	inx
	txa
	jsr     _scroll
	lda     #$00
	jsr     pusha
	jsr     _sfx_play
	lda     #$00
	sta     _i
	tax
L1227:	lda     _i
	cmp     #$10
	bcs     L122A
	lda     #$02
	jsr     pusha
	lda     _i
	and     #$01
	beq     L1228
	lda     #$0F
	jmp     L1229
L1228:	lda     #$20
L1229:	jsr     _pal_col
	lda     #$04
	jsr     _delay
	ldx     #$00
	inc     _i
	jmp     L1227
L122A:	txa
	jmp     _pal_fade_to

.endproc

; ---------------------------------------------------------------
; void __near__ show_screen (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_screen: near

.segment	"CODE"

	jsr     pusha
	ldx     #$FF
	lda     #$FC
	jsr     pushax
	inx
	txa
	jsr     _scroll
	ldy     #$00
	lda     (sp),y
	cmp     #$05
	bcs     L122F
	tya
	jmp     L122C
L122F:	lda     (sp),y
	sec
	sbc     #$05
	clc
	adc     #$01
L122C:	sta     _spr
	ldx     #$20
	tya
	jsr     _vram_adr
	ldx     #$00
	lda     _spr
	asl     a
	bcc     L122D
	inx
	clc
L122D:	adc     #<(_screenList)
	sta     ptr1
	txa
	adc     #>(_screenList)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _vram_unrle
	lda     _spr
	bne     L0F1F
	tay
	lda     (sp),y
	asl     a
	sta     _j
	ldx     #$21
	lda     #$94
	sta     _i16
	stx     _i16+1
	sty     _i
L1230:	lda     _i
	cmp     #$03
	bcs     L0F1F
	lda     _i16
	ldx     _i16+1
	jsr     _vram_adr
	ldy     _j
	lda     _largeNums,y
	jsr     _vram_put
	ldx     #$00
	lda     _j
	clc
	adc     #$01
	bcc     L0F2F
	inx
L0F2F:	sta     ptr1
	txa
	clc
	adc     #>(_largeNums)
	sta     ptr1+1
	ldy     #<(_largeNums)
	lda     (ptr1),y
	jsr     _vram_put
	lda     #$0A
	clc
	adc     _j
	sta     _j
	lda     #$20
	clc
	adc     _i16
	sta     _i16
	bcc     L0F34
	inc     _i16+1
L0F34:	inc     _i
	jmp     L1230
L0F1F:	ldy     #$00
	lda     (sp),y
	cmp     #$05
	bne     L0F39
	ldx     #$15
	lda     #$25
	jmp     L0F3B
L0F39:	ldx     #$11
	lda     #$21
L0F3B:	sta     _i16
	stx     _i16+1
	sty     _frame_cnt
	lda     #$02
	jsr     pusha
	lda     _i16
	jsr     _pal_col
	lda     #$03
	jsr     pusha
	lda     #$30
	jsr     _pal_col
	lda     #$06
	jsr     pusha
	lda     #$30
	jsr     _pal_col
	jsr     _ppu_on_bg
	ldx     #$00
	lda     #$04
	jsr     _pal_fade_to
	ldy     _spr
	lda     _screenMusicList,y
	jsr     _music_play
	lda     _spr
	bne     L0F54
	lda     #$32
	jsr     _delay
	jmp     L0F55
L0F54:	jsr     _ppu_wait_frame
	lda     #$02
	jsr     pusha
	lda     _frame_cnt
	and     #$02
	beq     L1231
	lda     _i16
	jmp     L1232
L1231:	lda     _i16+1
L1232:	jsr     _pal_col
	lda     #$00
	jsr     _pad_trigger
	ldx     #$00
	and     #$10
	bne     L1233
	inc     _frame_cnt
	jmp     L0F54
L0F55:	ldx     #$00
L1233:	txa
	jsr     _pal_fade_to
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ player_move (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_player_move: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L1238
	inx
	clc
L1238:	adc     #<(_player_x)
	sta     ptr1
	txa
	adc     #>(_player_x)
	sta     ptr1+1
	lda     (ptr1),y
	sta     _px
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L1239
	inx
	clc
L1239:	adc     #<(_player_y)
	sta     ptr1
	txa
	adc     #>(_player_y)
	sta     ptr1+1
	lda     (ptr1),y
	sta     _py
	ldx     #$00
	lda     (sp,x)
	cmp     #$01
	beq     L123C
	cmp     #$02
	beq     L123B
	cmp     #$04
	beq     L123E
	cmp     #$08
	beq     L123D
	jmp     L123F
L123B:	dec     _px
	jmp     L123F
L123C:	inc     _px
	jmp     L123F
L123D:	dec     _py
	jmp     L123F
L123E:	inc     _py
L123F:	lda     _py
	sec
	sbc     #$02
	bcs     L0F85
	dex
L0F85:	jsr     shlax4
	sta     ptr1
	stx     ptr1+1
	lda     _px
	ora     ptr1
	sta     ptr1
	lda     ptr1+1
	clc
	adc     #>(_map)
	sta     ptr1+1
	ldy     #<(_map)
	lda     (ptr1),y
	cmp     #$40
	beq     L0F66
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L123A
	inx
	clc
L123A:	adc     #<(_player_cnt)
	sta     ptr1
	txa
	adc     #>(_player_cnt)
	sta     ptr1+1
	lda     #$00
	dey
	sta     (ptr1),y
	iny
	tya
	sta     (ptr1),y
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     _player_dir,x
L0F66:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ put_num (unsigned int, unsigned int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_put_num: near

.segment	"CODE"

	jsr     pusha
	ldy     #$04
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _vram_adr
	ldy     #$00
	lda     (sp),y
	cmp     #$03
	bcc     L1241
	ldy     #$04
	jsr     pushwysp
	lda     #$64
	jsr     tosudiva0
	clc
	adc     #$10
	jsr     _vram_put
	ldy     #$00
L1241:	lda     (sp),y
	cmp     #$02
	bcc     L0F96
	ldy     #$04
	jsr     pushwysp
	lda     #$0A
	jsr     tosudiva0
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	clc
	adc     #$10
	jsr     _vram_put
L0F96:	ldy     #$04
	jsr     pushwysp
	lda     #$0A
	jsr     tosumoda0
	clc
	adc     #$10
	jsr     _vram_put
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ game_loop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_loop: near

.segment	"CODE"

	jsr     _oam_clear
	lda     _game_level
	asl     a
	sta     _i
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1272
	inx
	clc
L1272:	adc     #<(_levelList)
	sta     ptr1
	txa
	adc     #>(_levelList)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _vram_unrle
	ldx     #$20
	lda     #$42
	jsr     _vram_adr
	lda     #<(_statsStr)
	ldx     #>(_statsStr)
	jsr     pushax
	ldx     #$00
	lda     #$1B
	jsr     _vram_write
	ldx     #$00
	lda     _i
	clc
	adc     #$01
	bcc     L0FAF
	inx
L0FAF:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(_levelList)
	sta     ptr1
	lda     tmp1
	adc     #>(_levelList)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _pal_bg
	lda     #<(_palGameSpr)
	ldx     #>(_palGameSpr)
	jsr     _pal_spr
	lda     #$00
	sta     _player_all
	sta     _items_count
	sta     _items_collected
	ldx     #$20
	lda     #$80
	sta     _i16
	stx     _i16+1
	lda     #$00
	sta     _ptr
	sta     _wait
	lda     #$02
	sta     _i
L129B:	lda     _i
	cmp     #$0F
	jcs     L0FBF
	lda     _i16
	ldx     _i16+1
	jsr     _vram_adr
	lda     #<(_nameRow)
	ldx     #>(_nameRow)
	jsr     pushax
	ldx     #$00
	lda     #$20
	jsr     _vram_read
	lda     _i16
	ldx     _i16+1
	jsr     _vram_adr
	lda     #$00
L126D:	sta     _j
	cmp     #$20
	jcs     L0FCE
	ldy     _j
	lda     _nameRow,y
	sta     _spr
	cmp     #$10
	beq     L0FE4
	cmp     #$11
	beq     L0FE4
	cmp     #$12
	beq     L0FE4
	cmp     #$13
	beq     L0FE4
	cmp     #$45
	jeq     L129D
	jmp     L129E
L0FE4:	ldy     _player_all
	lda     #$00
	sta     _player_dir,y
	tax
	lda     _player_all
	asl     a
	bcc     L1273
	inx
	clc
L1273:	adc     #<(_player_x)
	sta     ptr1
	txa
	adc     #>(_player_x)
	sta     ptr1+1
	ldx     #$00
	lda     _j
	jsr     aslax3
	jsr     aslax4
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldx     #$00
	lda     _player_all
	asl     a
	bcc     L1274
	inx
	clc
L1274:	adc     #<(_player_y)
	sta     ptr1
	txa
	adc     #>(_player_y)
	sta     ptr1+1
	ldx     #$00
	lda     _i
	jsr     aslax4
	jsr     aslax4
	dey
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldx     #$00
	lda     _player_all
	asl     a
	bcc     L1275
	inx
	clc
L1275:	adc     #<(_player_cnt)
	sta     ptr1
	txa
	adc     #>(_player_cnt)
	sta     ptr1+1
	lda     #$00
	dey
	sta     (ptr1),y
	iny
	sta     (ptr1),y
	lda     #<(_player_wait)
	ldx     #>(_player_wait)
	clc
	adc     _player_all
	bcc     L0FF6
	inx
L0FF6:	sta     ptr1
	stx     ptr1+1
	lda     _spr
	sec
	sbc     #$10
	asl     a
	asl     a
	asl     a
	asl     a
	clc
	adc     #$10
	dey
	sta     (ptr1),y
	ldx     #$00
	lda     _player_all
	asl     a
	bcc     L1276
	inx
	clc
L1276:	adc     #<(_player_speed)
	sta     ptr1
	txa
	adc     #>(_player_speed)
	sta     ptr1+1
	ldx     #$00
	lda     _spr
	cmp     #$10
	bne     L129C
	lda     #$20
	jmp     L12CF
L129C:	lda     _spr
	sec
	sbc     #$11
	bcs     L1006
	dex
L1006:	stx     tmp1
	asl     a
	rol     tmp1
	ldx     tmp1
	clc
	adc     #$0A
	bcc     L12CF
	inx
L12CF:	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	inc     _player_all
	lda     #$10
	clc
	adc     _wait
	sta     _wait
	lda     #$44
	sta     _spr
	jmp     L129E
L129D:	inc     _items_count
L129E:	lda     _ptr
	inc     _ptr
	clc
	adc     #<(_map)
	sta     ptr1
	lda     #$00
	adc     #>(_map)
	sta     ptr1+1
	lda     _spr
	ldy     #$00
	sta     (ptr1),y
	lda     _spr
	jsr     _vram_put
	ldx     #$00
	lda     _j
	clc
	adc     #$01
	bcc     L1018
	inx
L1018:	sta     ptr1
	txa
	clc
	adc     #>(_nameRow)
	sta     ptr1+1
	ldy     #<(_nameRow)
	lda     (ptr1),y
	jsr     _vram_put
	lda     #$02
	clc
	adc     _j
	jmp     L126D
L0FCE:	lda     #$40
	clc
	adc     _i16
	sta     _i16
	bcc     L101B
	inc     _i16+1
L101B:	inc     _i
	jmp     L129B
L0FBF:	lda     #<(_update_list)
	ldx     #>(_update_list)
	jsr     pushax
	lda     #<(_updateListData)
	ldx     #>(_updateListData)
	jsr     pushax
	ldx     #$00
	lda     #$16
	jsr     _memcpy
	lda     #<(_update_list)
	ldx     #>(_update_list)
	jsr     _set_vram_update
	jsr     decsp4
	lda     #$48
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$20
	sta     (sp),y
	ldx     #$00
	lda     _game_level
	clc
	adc     #$01
	bcc     L1026
	inx
L1026:	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	tya
	jsr     _put_num
	jsr     decsp4
	lda     #$53
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$20
	sta     (sp),y
	lda     _items_count
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$03
	jsr     _put_num
	jsr     decsp4
	lda     #$5D
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$20
	sta     (sp),y
	ldx     #$00
	lda     _game_lives
	sec
	sbc     #$01
	bcs     L102F
	dex
L102F:	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	tya
	jsr     _put_num
	jsr     _ppu_on_all
	lda     #$00
	sta     _game_done
	sta     _game_paused
	sta     _game_clear
	sta     _bright
	sta     _frame_cnt
	jmp     L1097
L103C:	lda     _player_all
	sec
	sbc     #$01
	asl     a
	asl     a
	asl     a
	asl     a
	sta     _spr
	lda     #$00
	sta     _i
	tax
L129F:	lda     _i
	cmp     _player_all
	jcs     L1045
	asl     a
	bcc     L1277
	inx
	clc
L1277:	adc     #<(_player_y)
	sta     ptr1
	txa
	adc     #>(_player_y)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     shrax4
	sta     _py
	ldy     _i
	lda     _player_wait,y
	beq     L1053
	ldy     _i
	lda     _player_wait,y
	cmp     #$10
	bcs     L12A0
	ldy     _i
	lda     _player_wait,y
	and     #$02
	beq     L1053
L12A0:	lda     #$F0
	sta     _py
L1053:	jsr     decsp3
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1278
	inx
	clc
L1278:	adc     #<(_player_x)
	sta     ptr1
	txa
	adc     #>(_player_x)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     shrax4
	ldy     #$02
	sta     (sp),y
	lda     _py
	dey
	sta     (sp),y
	lda     _spr
	dey
	sta     (sp),y
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1279
	inx
	clc
L1279:	adc     #<(_sprListPlayer)
	sta     ptr1
	txa
	adc     #>(_sprListPlayer)
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _oam_meta_spr
	lda     _spr
	sec
	sbc     #$10
	sta     _spr
	ldx     #$00
	inc     _i
	jmp     L129F
L1045:	jsr     _ppu_wait_frame
	inc     _frame_cnt
	lda     _frame_cnt
	and     #$03
	bne     L1067
	lda     _game_paused
	bne     L106A
	lda     _bright
	cmp     #$04
	bcs     L106A
	inc     _bright
L106A:	lda     _game_paused
	beq     L106F
	lda     _bright
	cmp     #$03
	bcc     L106F
	dec     _bright
L106F:	lda     _bright
	jsr     _pal_bright
L1067:	lda     #$00
	jsr     _pad_trigger
	sta     _i
	and     #$10
	beq     L1079
	lda     _game_paused
	eor     #$01
	sta     _game_paused
	jsr     _music_pause
L1079:	lda     _game_paused
	jne     L1097
	lda     _frame_cnt
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	and     #$01
	jsr     _bank_bg
	lda     _frame_cnt
	lsr     a
	lsr     a
	lsr     a
	and     #$01
	jsr     _bank_spr
	lda     _wait
	beq     L12A6
	dec     _wait
	bne     L12A6
	lda     #$01
	jsr     _music_play
L12A6:	lda     _items_count
	cmp     _items_collected
	bne     L12A7
	lda     #$02
	jsr     _music_play
	lda     #$01
	sta     _game_done
	sta     _game_clear
L12A7:	lda     #$00
	sta     _i
	tax
L12A8:	lda     _i
	cmp     _player_all
	txa
	sbc     #$00
	jcs     L1097
	ldy     _i
	lda     _player_wait,y
	beq     L109E
	ldy     _i
	lda     _player_wait,y
	cmp     #$10
	bne     L10A2
	lda     _i
	beq     L12A9
	lda     #$03
	jmp     L12AA
L12A9:	lda     #$02
L12AA:	jsr     pusha
	lda     _i
	jsr     _sfx_play
L10A2:	lda     #<(_player_wait)
	ldx     #>(_player_wait)
	clc
	adc     _i
	bcc     L10AF
	inx
L10AF:	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     (ptr1),y
	sec
	sbc     #$01
	sta     (ptr1),y
	jmp     L12C8
L109E:	lda     _wait
	jne     L12C8
	lda     _i
	jeq     L12AB
	asl     a
	bcc     L127A
	ldx     #$01
	clc
L127A:	adc     #<(_player_x)
	sta     ptr1
	txa
	adc     #>(_player_x)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$40
	bcc     L10BA
	inx
L10BA:	jsr     pushax
	lda     _player_x
	ldx     _player_x+1
	clc
	adc     #$C0
	bcc     L10BE
	inx
L10BE:	jsr     tosicmp
	jcs     L10B6
	ldx     #$00
	lda     _i
	asl     a
	bcc     L127B
	inx
	clc
L127B:	adc     #<(_player_x)
	sta     ptr1
	txa
	adc     #>(_player_x)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$C0
	bcc     L10C2
	inx
L10C2:	jsr     pushax
	lda     _player_x
	ldx     _player_x+1
	clc
	adc     #$40
	bcc     L10C6
	inx
L10C6:	jsr     tosicmp
	bcc     L10B6
	ldx     #$00
	lda     _i
	asl     a
	bcc     L127C
	inx
	clc
L127C:	adc     #<(_player_y)
	sta     ptr1
	txa
	adc     #>(_player_y)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$40
	bcc     L10CA
	inx
L10CA:	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	clc
	adc     #$C0
	bcc     L10CE
	inx
L10CE:	jsr     tosicmp
	bcs     L10B6
	ldx     #$00
	lda     _i
	asl     a
	bcc     L127D
	inx
	clc
L127D:	adc     #<(_player_y)
	sta     ptr1
	txa
	adc     #>(_player_y)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$C0
	bcc     L10D2
	inx
L10D2:	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	clc
	adc     #$40
	bcc     L10D6
	inx
L10D6:	jsr     tosicmp
	bcc     L10B6
	lda     #$00
	jmp     L10D7
L10B6:	lda     #$01
L10D7:	jsr     bnega
	beq     L10D8
	lda     _game_clear
	bne     L10D8
	lda     #$05
	jsr     _music_play
	lda     #$01
	sta     _game_done
	jmp     L1097
L10D8:	ldx     #$00
L12AB:	lda     _i
	asl     a
	bcc     L127E
	ldx     #$01
	clc
L127E:	adc     #<(_player_cnt)
	sta     ptr1
	txa
	adc     #>(_player_cnt)
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L1134
	ldy     _i
	ldx     #$00
	lda     _player_dir,y
	cmp     #$01
	beq     L12AC
	cmp     #$02
	beq     L12AD
	cmp     #$04
	beq     L12AE
	cmp     #$08
	jeq     L12AF
	jmp     L12B0
L12AC:	lda     _i
	asl     a
	bcc     L127F
	inx
	clc
L127F:	adc     #<(_player_x)
	tay
	txa
	adc     #>(_player_x)
	tax
	tya
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1280
	inx
	clc
L1280:	adc     #<(_player_speed)
	sta     ptr1
	txa
	adc     #>(_player_speed)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tosaddax
	jmp     L12C9
L12AD:	lda     _i
	asl     a
	bcc     L1281
	inx
	clc
L1281:	adc     #<(_player_x)
	tay
	txa
	adc     #>(_player_x)
	jmp     L12E8
L12AE:	lda     _i
	asl     a
	bcc     L1283
	inx
	clc
L1283:	adc     #<(_player_y)
	tay
	txa
	adc     #>(_player_y)
	tax
	tya
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1284
	inx
	clc
L1284:	adc     #<(_player_speed)
	sta     ptr1
	txa
	adc     #>(_player_speed)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tosaddax
	jmp     L12C9
L12AF:	lda     _i
	asl     a
	bcc     L1285
	inx
	clc
L1285:	adc     #<(_player_y)
	tay
	txa
	adc     #>(_player_y)
L12E8:	tax
	tya
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1286
	inx
	clc
L1286:	adc     #<(_player_speed)
	sta     ptr1
	txa
	adc     #>(_player_speed)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tossubax
L12C9:	ldy     #$00
	jsr     staxspidx
	ldx     #$00
L12B0:	lda     _i
	asl     a
	bcc     L1287
	inx
	clc
L1287:	adc     #<(_player_cnt)
	tay
	txa
	adc     #>(_player_cnt)
	tax
	tya
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1288
	inx
	clc
L1288:	adc     #<(_player_speed)
	sta     ptr1
	txa
	adc     #>(_player_speed)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tossubax
	ldy     #$00
	jsr     staxspidx
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1289
	inx
	clc
L1289:	adc     #<(_player_cnt)
	sta     ptr1
	txa
	adc     #>(_player_cnt)
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	cmp     #$01
	txa
	sbc     #$00
	bvc     L1105
	eor     #$80
L1105:	asl     a
	ldx     #$00
	jcc     L12B1
	lda     _i
	asl     a
	bcc     L128A
	inx
	clc
L128A:	adc     #<(_player_cnt)
	sta     ptr1
	txa
	adc     #>(_player_cnt)
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	cpx     #$80
	jcc     L1106
	ldx     #$00
	lda     _i
	asl     a
	bcc     L128B
	inx
	clc
L128B:	adc     #<(_player_cnt)
	sta     ptr1
	txa
	adc     #>(_player_cnt)
	sta     ptr1+1
	lda     #$00
	dey
	sta     (ptr1),y
	iny
	sta     (ptr1),y
	tax
	lda     _i
	asl     a
	bcc     L128C
	inx
	clc
L128C:	adc     #<(_player_x)
	sta     sreg
	txa
	adc     #>(_player_x)
	sta     sreg+1
	ldx     #$00
	lda     _i
	asl     a
	bcc     L128D
	inx
	clc
L128D:	adc     #<(_player_x)
	sta     ptr1
	txa
	adc     #>(_player_x)
	sta     ptr1+1
	lda     (ptr1),y
	sta     ptr1+1
	ldy     _i
	ldx     #$00
	lda     _player_dir,y
	cmp     #$02
	bne     L126F
	inx
L126F:	lda     #$00
	clc
	pha
	txa
	adc     ptr1+1
	tax
	pla
	ldy     #$00
	sta     (sreg),y
	iny
	txa
	sta     (sreg),y
	ldx     #$00
	lda     _i
	asl     a
	bcc     L128E
	inx
	clc
L128E:	adc     #<(_player_y)
	sta     sreg
	txa
	adc     #>(_player_y)
	sta     sreg+1
	ldx     #$00
	lda     _i
	asl     a
	bcc     L128F
	inx
	clc
L128F:	adc     #<(_player_y)
	sta     ptr1
	txa
	adc     #>(_player_y)
	sta     ptr1+1
	lda     (ptr1),y
	sta     ptr1+1
	ldy     _i
	ldx     #$00
	lda     _player_dir,y
	cmp     #$08
	bne     L1270
	inx
L1270:	lda     #$00
	clc
	pha
	txa
	adc     ptr1+1
	tax
	pla
	ldy     #$00
	sta     (sreg),y
	iny
	txa
	sta     (sreg),y
L1106:	lda     _i
	jne     L1134
	tax
	lda     _i
	asl     a
	bcc     L1290
	inx
	clc
L1290:	adc     #<(_player_y)
	sta     ptr1
	txa
	adc     #>(_player_y)
	sta     ptr1+1
	lda     (ptr1),y
	ldx     #$00
	sec
	sbc     #$02
	bcs     L112F
	dex
L112F:	jsr     shlax4
	sta     sreg
	stx     sreg+1
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1291
	inx
	clc
L1291:	adc     #<(_player_x)
	sta     ptr1
	txa
	adc     #>(_player_x)
	sta     ptr1+1
	lda     (ptr1),y
	ora     sreg
	sta     _i16
	lda     sreg+1
	sta     _i16+1
	lda     #<(_map)
	sta     ptr1
	lda     #>(_map)
	clc
	adc     _i16+1
	sta     ptr1+1
	ldy     _i16
	ldx     #$00
	lda     (ptr1),y
	cmp     #$45
	jne     L12B1
	lda     #<(_map)
	clc
	adc     _i16
	sta     ptr1
	lda     #>(_map)
	adc     _i16+1
	sta     ptr1+1
	lda     #$44
	ldy     #$00
	sta     (ptr1),y
	lda     #$01
	jsr     pusha
	lda     #$02
	jsr     _sfx_play
	inc     _items_collected
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1292
	inx
	clc
L1292:	adc     #<(_player_y)
	sta     ptr1
	txa
	adc     #>(_player_y)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	ldx     #$00
	sec
	sbc     #$02
	bcs     L1145
	dex
L1145:	jsr     shlax4
	jsr     shlax2
	clc
	adc     #$80
	sta     sreg
	txa
	adc     #$20
	sta     sreg+1
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1293
	inx
	clc
L1293:	adc     #<(_player_x)
	sta     ptr1
	txa
	adc     #>(_player_x)
	sta     ptr1+1
	lda     (ptr1),y
	ldx     #$00
	asl     a
	bcc     L126B
	inx
L126B:	ora     sreg
	sta     _i16
	txa
	ora     sreg+1
	sta     _i16+1
	sta     _update_list
	lda     _i16
	sta     _update_list+1
	lda     _update_list
	sta     _update_list+3
	lda     _update_list+1
	clc
	adc     #$01
	sta     _update_list+4
	lda     #$20
	clc
	adc     _i16
	sta     _i16
	bcc     L115B
	inc     _i16+1
L115B:	lda     _i16+1
	sta     _update_list+6
	lda     _i16
	sta     _update_list+7
	lda     _update_list+6
	sta     _update_list+9
	lda     _update_list+7
	clc
	adc     #$01
	sta     _update_list+10
	lda     _items_collected
	jsr     pusha0
	lda     #$64
	jsr     tosudiva0
	clc
	adc     #$10
	sta     _update_list+14
	lda     _items_collected
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	clc
	adc     #$10
	sta     _update_list+17
	lda     _items_collected
	jsr     pusha0
	lda     #$0A
	jsr     tosumoda0
	clc
	adc     #$10
	sta     _update_list+20
L1134:	ldx     #$00
L12B1:	lda     _i
	asl     a
	bcc     L1294
	inx
	clc
L1294:	adc     #<(_player_cnt)
	sta     ptr1
	txa
	adc     #>(_player_cnt)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     bnegax
	jeq     L1098
	lda     _i
	bne     L117A
	jsr     _pad_state
	sta     _j
	lda     _player_dir
	and     _j
	pha
	pla
	beq     L12B2
	lda     _player_dir
	eor     #$FF
	and     _j
	sta     _j
	lda     _i
	jsr     pusha
	lda     _player_dir
	jsr     _player_move
L12B2:	lda     _j
	and     #$02
	beq     L12B3
	lda     _i
	jsr     pusha
	lda     #$02
	jsr     _player_move
L12B3:	lda     _j
	and     #$01
	beq     L12B4
	lda     _i
	jsr     pusha
	lda     #$01
	jsr     _player_move
L12B4:	lda     _j
	and     #$08
	beq     L12B5
	lda     _i
	jsr     pusha
	lda     #$08
	jsr     _player_move
L12B5:	lda     _j
	ldx     #$00
	and     #$04
	jeq     L12C8
	lda     _i
	jsr     pusha
	lda     #$04
	jmp     L1271
L117A:	ldx     #$00
	lda     _i
	asl     a
	bcc     L1295
	inx
	clc
L1295:	adc     #<(_player_y)
	sta     ptr1
	txa
	adc     #>(_player_y)
	sta     ptr1+1
	iny
	lda     (ptr1),y
	ldx     #$00
	sec
	sbc     #$02
	bcs     L11A6
	dex
L11A6:	jsr     shlax4
	sta     sreg
	stx     sreg+1
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1296
	inx
	clc
L1296:	adc     #<(_player_x)
	sta     ptr1
	txa
	adc     #>(_player_x)
	sta     ptr1+1
	lda     (ptr1),y
	ora     sreg
	sta     _i16
	lda     sreg+1
	sta     _i16+1
	ldy     _i
	lda     _player_dir,y
	sta     _ptr
	lda     #$00
	sta     _j
	lda     _ptr
	cmp     #$01
	beq     L12B8
	lda     _i16
	ldx     _i16+1
	sec
	sbc     #$01
	bcs     L11B4
	dex
L11B4:	sta     ptr1
	txa
	clc
	adc     #>(_map)
	sta     ptr1+1
	ldy     #<(_map)
	lda     (ptr1),y
	cmp     #$40
	beq     L12B8
	lda     _j
	inc     _j
	clc
	adc     #<(_dir)
	sta     ptr1
	lda     #$00
	adc     #>(_dir)
	sta     ptr1+1
	lda     #$02
	ldy     #$00
	sta     (ptr1),y
L12B8:	lda     _ptr
	cmp     #$02
	beq     L12BB
	lda     _i16
	ldx     _i16+1
	clc
	adc     #$01
	bcc     L11BD
	inx
L11BD:	sta     ptr1
	txa
	clc
	adc     #>(_map)
	sta     ptr1+1
	ldy     #<(_map)
	lda     (ptr1),y
	cmp     #$40
	beq     L12BB
	lda     _j
	inc     _j
	clc
	adc     #<(_dir)
	sta     ptr1
	lda     #$00
	adc     #>(_dir)
	sta     ptr1+1
	lda     #$01
	ldy     #$00
	sta     (ptr1),y
L12BB:	lda     _ptr
	cmp     #$04
	beq     L12BE
	lda     _i16
	ldx     _i16+1
	sec
	sbc     #$10
	bcs     L11C6
	dex
L11C6:	sta     ptr1
	txa
	clc
	adc     #>(_map)
	sta     ptr1+1
	ldy     #<(_map)
	lda     (ptr1),y
	cmp     #$40
	beq     L12BE
	lda     _j
	inc     _j
	clc
	adc     #<(_dir)
	sta     ptr1
	lda     #$00
	adc     #>(_dir)
	sta     ptr1+1
	lda     #$08
	ldy     #$00
	sta     (ptr1),y
L12BE:	lda     _ptr
	cmp     #$08
	beq     L11CB
	lda     _i16
	ldx     _i16+1
	clc
	adc     #$10
	bcc     L11CF
	inx
L11CF:	sta     ptr1
	txa
	clc
	adc     #>(_map)
	sta     ptr1+1
	ldy     #<(_map)
	lda     (ptr1),y
	cmp     #$40
	beq     L11CB
	lda     _j
	inc     _j
	clc
	adc     #<(_dir)
	sta     ptr1
	lda     #$00
	adc     #>(_dir)
	sta     ptr1+1
	lda     #$04
	ldy     #$00
	sta     (ptr1),y
L11CB:	lda     _i
	jsr     pusha
	jsr     _rand8
	jsr     pushax
	lda     _j
	jsr     tosumoda0
	sta     ptr1
	txa
	clc
	adc     #>(_dir)
	sta     ptr1+1
	ldy     #<(_dir)
	lda     (ptr1),y
	jsr     _player_move
	lda     _j
	cmp     #$02
	ldx     #$00
	jcc     L12C8
	lda     _ptr
	cmp     #$04
	beq     L12C2
	lda     _player_y
	ldx     _player_y+1
	jsr     pushax
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1297
	inx
	clc
L1297:	adc     #<(_player_y)
	sta     ptr1
	txa
	adc     #>(_player_y)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tosicmp
	bcs     L12CA
	lda     _i
	jsr     pusha
	lda     #$08
	jsr     _player_move
L12CA:	ldx     #$00
L12C2:	lda     _ptr
	cmp     #$08
	beq     L12C4
	lda     _player_y
	ldx     _player_y+1
	jsr     pushax
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1298
	inx
	clc
L1298:	adc     #<(_player_y)
	sta     ptr1
	txa
	adc     #>(_player_y)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tosicmp
	beq     L12CB
	bcc     L12CB
	lda     _i
	jsr     pusha
	lda     #$04
	jsr     _player_move
L12CB:	ldx     #$00
L12C4:	lda     _ptr
	cmp     #$01
	beq     L12C6
	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	ldx     #$00
	lda     _i
	asl     a
	bcc     L1299
	inx
	clc
L1299:	adc     #<(_player_x)
	sta     ptr1
	txa
	adc     #>(_player_x)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tosicmp
	bcs     L12CC
	lda     _i
	jsr     pusha
	lda     #$02
	jsr     _player_move
L12CC:	ldx     #$00
L12C6:	lda     _ptr
	cmp     #$02
	beq     L12C8
	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	ldx     #$00
	lda     _i
	asl     a
	bcc     L129A
	inx
	clc
L129A:	adc     #<(_player_x)
	sta     ptr1
	txa
	adc     #>(_player_x)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tosicmp
	beq     L1098
	bcc     L1098
	lda     _i
	jsr     pusha
	lda     #$01
L1271:	jsr     _player_move
L1098:	ldx     #$00
L12C8:	inc     _i
	jmp     L12A8
L1097:	lda     _game_done
	jeq     L103C
	lda     #$64
	jsr     _delay
	ldx     #$00
	txa
	jmp     _pal_fade_to

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

L1203:	jsr     _title_screen
	lda     #$00
	sta     _game_level
	lda     #$04
	sta     _game_lives
	jmp     L1218
L120C:	lda     _game_level
	jsr     _show_screen
	jsr     _game_loop
	lda     _game_clear
	beq     L1215
	inc     _game_level
	jmp     L1218
L1215:	dec     _game_lives
L1218:	lda     _game_lives
	beq     L12E9
	lda     _game_level
	cmp     #$05
	bcc     L120C
L12E9:	lda     _game_lives
	bne     L12ED
	lda     #$05
	jmp     L12EE
L12ED:	lda     #$06
L12EE:	jsr     _show_screen
	jmp     L1203

.endproc

