;this file for FamiTone2 library generated by text2data tool

paisleyOwl_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,245,204

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env6
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $f0 ;instrument $03
	.word @env3,@env0,@env0
	.byte $00
	.byte $f0 ;instrument $04
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env1,@env5,@env0
	.byte $00
	.byte $f0 ;instrument $06
	.word @env3,@env4,@env0
	.byte $00

@samples:
	.byte $00+FT_DPCM_PTR,$00,$00	;1
	.byte $00+FT_DPCM_PTR,$00,$00	;2
	.byte $00+FT_DPCM_PTR,$00,$00	;3
	.byte $00+FT_DPCM_PTR,$00,$00	;4
	.byte $00+FT_DPCM_PTR,$00,$00	;5
	.byte $00+FT_DPCM_PTR,$00,$00	;6
	.byte $00+FT_DPCM_PTR,$00,$00	;7
	.byte $00+FT_DPCM_PTR,$00,$00	;8
	.byte $00+FT_DPCM_PTR,$00,$00	;9
	.byte $00+FT_DPCM_PTR,$00,$00	;10
	.byte $00+FT_DPCM_PTR,$00,$00	;11
	.byte $00+FT_DPCM_PTR,$00,$00	;12
	.byte $00+FT_DPCM_PTR,$00,$00	;13
	.byte $00+FT_DPCM_PTR,$00,$00	;14
	.byte $00+FT_DPCM_PTR,$00,$00	;15
	.byte $00+FT_DPCM_PTR,$00,$00	;16
	.byte $00+FT_DPCM_PTR,$00,$00	;17
	.byte $00+FT_DPCM_PTR,$00,$00	;18
	.byte $00+FT_DPCM_PTR,$00,$00	;19
	.byte $00+FT_DPCM_PTR,$00,$00	;20
	.byte $00+FT_DPCM_PTR,$00,$00	;21
	.byte $00+FT_DPCM_PTR,$00,$00	;22
	.byte $00+FT_DPCM_PTR,$00,$00	;23
	.byte $00+FT_DPCM_PTR,$00,$00	;24
	.byte $00+FT_DPCM_PTR,$2e,$0f	;25
	.byte $00+FT_DPCM_PTR,$00,$00	;26
	.byte $00+FT_DPCM_PTR,$00,$00	;27
	.byte $00+FT_DPCM_PTR,$00,$00	;28
	.byte $00+FT_DPCM_PTR,$00,$00	;29
	.byte $00+FT_DPCM_PTR,$00,$00	;30
	.byte $00+FT_DPCM_PTR,$00,$00	;31
	.byte $00+FT_DPCM_PTR,$00,$00	;32
	.byte $00+FT_DPCM_PTR,$00,$00	;33
	.byte $00+FT_DPCM_PTR,$00,$00	;34
	.byte $00+FT_DPCM_PTR,$00,$00	;35
	.byte $00+FT_DPCM_PTR,$00,$00	;36
	.byte $00+FT_DPCM_PTR,$00,$00	;37
	.byte $00+FT_DPCM_PTR,$00,$00	;38
	.byte $00+FT_DPCM_PTR,$00,$00	;39
	.byte $00+FT_DPCM_PTR,$00,$00	;40
	.byte $00+FT_DPCM_PTR,$00,$00	;41
	.byte $00+FT_DPCM_PTR,$00,$00	;42
	.byte $00+FT_DPCM_PTR,$00,$00	;43
	.byte $00+FT_DPCM_PTR,$00,$00	;44
	.byte $00+FT_DPCM_PTR,$00,$00	;45
	.byte $00+FT_DPCM_PTR,$00,$00	;46
	.byte $00+FT_DPCM_PTR,$00,$00	;47
	.byte $00+FT_DPCM_PTR,$00,$00	;48
	.byte $00+FT_DPCM_PTR,$00,$00	;49
	.byte $00+FT_DPCM_PTR,$00,$00	;50
	.byte $00+FT_DPCM_PTR,$00,$00	;51
	.byte $00+FT_DPCM_PTR,$00,$00	;52
	.byte $00+FT_DPCM_PTR,$00,$00	;53
	.byte $00+FT_DPCM_PTR,$00,$00	;54
	.byte $00+FT_DPCM_PTR,$00,$00	;55
	.byte $00+FT_DPCM_PTR,$00,$00	;56
	.byte $00+FT_DPCM_PTR,$00,$00	;57
	.byte $00+FT_DPCM_PTR,$00,$00	;58
	.byte $00+FT_DPCM_PTR,$00,$00	;59
	.byte $00+FT_DPCM_PTR,$00,$00	;60
	.byte $00+FT_DPCM_PTR,$00,$00	;61
	.byte $00+FT_DPCM_PTR,$00,$00	;62
	.byte $00+FT_DPCM_PTR,$00,$00	;63

@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$ce,$c3,$c1,$c2,$c3,$00,$04
@env2:
	.byte $cf,$ce,$ce,$cc,$ca,$c7,$c5,$c4,$c3,$c0,$00,$09
@env3:
	.byte $cf,$ce,$cc,$c9,$c2,$c2,$c3,$c4,$c4,$c5,$c5,$c7,$00,$0b
@env4:
	.byte $c0,$bf,$bf,$be,$be,$bf,$04,$be,$02,$c5,$c1,$c1,$00,$09
@env5:
	.byte $c0,$b4,$b7,$c2,$c2,$c1,$00,$05
@env6:
	.byte $cd,$d0,$00,$01


@song0ch0:
	.byte $fb,$05
@song0ch0loop:
@ref0:
	.byte $e7,$8c,$56,$8b,$86,$58,$83,$8c,$5c,$81
@ref1:
	.byte $86,$28,$4d,$88,$36,$86,$4c,$36,$28,$88,$44,$86,$3a,$3b,$28,$36
	.byte $36,$88,$4e,$86,$28,$88,$3a,$8c,$4e,$83,$86,$52,$28,$3a,$88,$38
	.byte $86,$3a,$28,$88,$36,$86,$36,$56,$3b,$3a,$5c,$58,$5c,$88,$58,$86
	.byte $3a,$3a,$58,$88,$36,$86,$5c,$59,$3a,$3a,$28,$36,$37,$28,$3a,$3a
	.byte $28,$36,$36,$40,$88,$3a,$3a,$86,$28,$88,$36,$86,$4c,$2c,$83
@ref2:
	.byte $1e,$8d,$28,$8d,$88,$36,$8f,$86,$44,$8b,$88,$4e,$8b,$86,$58,$8f
	.byte $88,$4e,$85,$86,$4c,$87,$8c,$41,$3f,$36,$83
@ref3:
	.byte $80,$06,$8b,$0a,$89,$0f,$3b,$10,$89,$14,$8d,$1e,$1c,$89,$48,$1e
	.byte $89,$41,$1e,$26,$8b,$2d,$35,$37,$3b,$3e
@ref4:
	.byte $1c,$8d,$34,$8d,$88,$4c,$8d,$82,$04,$af,$88,$5d,$59,$48,$80,$57
	.byte $58,$4d,$5c,$4f,$58,$52
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref5:
	.byte $bf,$80,$26,$89,$26,$95,$26,$87,$34,$87,$36,$85
@ref6:
	.byte $f9,$85
@ref7:
	.byte $4c,$9f,$60,$4c,$5c,$52,$59,$52,$52,$4e,$34,$4e,$83,$4c,$83,$3e
	.byte $85,$35,$49,$44,$83,$41,$3e,$83,$3a,$34,$37,$34,$83,$30,$2c,$83
	.byte $27,$44,$81
@ref8:
	.byte $88,$26,$83,$8c,$36,$1e,$4e,$4e,$4e,$80,$44,$8c,$4f,$4f,$26,$83
	.byte $80,$34,$89,$35,$36,$89,$34,$28,$36,$83,$34,$83,$34,$8c,$27,$88
	.byte $28,$8d,$28,$89,$3f,$41,$45,$4d,$52
@ref9:
	.byte $26,$8d,$80,$44,$8c,$4f,$4f,$26,$83,$80,$34,$8c,$06,$87,$80,$34
	.byte $8c,$10,$80,$36,$af,$34,$36,$83,$3b,$3f,$41,$45,$48,$83
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref10:
	.byte $80,$44,$85,$53,$4f,$4c,$85,$44,$85,$40,$85,$4d,$40,$85,$4f,$4c
	.byte $85,$3e,$85,$52,$85,$4f,$4d,$4f,$3a,$85,$4d,$4f,$4d,$4e,$85,$52
	.byte $85
@ref11:
	.byte $44,$85,$53,$4f,$4c,$85,$44,$85,$40,$85,$4d,$40,$85,$4f,$4c,$85
	.byte $3e,$85,$52,$85,$4f,$4d,$4f,$3a,$85,$4d,$4f,$4d,$4e,$85,$52,$85
@ref12:
	.byte $44,$85,$53,$4e,$91,$40,$85,$4d,$40,$91,$3e,$85,$52,$85,$4e,$95
	.byte $8a,$2a,$2e,$2a,$2e,$20,$8d
@ref13:
	.byte $22,$80,$29,$28,$52,$28,$28,$83,$28,$29,$29,$29,$2d,$2d,$4c,$2c
	.byte $40,$2d,$2d,$2d,$2d,$2c,$2a,$1e,$1f,$1f,$1e,$42,$1f,$1f,$1f,$1f
	.byte $23,$23,$22,$8a,$2e,$22,$44,$20,$22,$23,$23,$22,$81
@ref14:
	.byte $22,$80,$29,$28,$52,$28,$28,$83,$28,$29,$8a,$28,$85,$80,$2d,$2c
	.byte $83,$2d,$2d,$2d,$2d,$2d,$2d,$88,$36,$3a,$3c,$83,$80,$1e,$3a,$36
	.byte $32,$8a,$3a,$8d,$80,$23,$22,$8a,$2e,$22,$44,$20,$22,$23,$23,$22
	.byte $81
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref15:
	.byte $87,$82,$0e,$8d,$0e,$8d,$0e,$8d,$0e,$8d,$0e,$8d,$0e,$8d,$0e,$83
	.byte $1e,$87,$0e,$85
@ref16:
	.byte $87,$0e,$8d,$0e,$8d,$0e,$8d,$0e,$8d,$0e,$8d,$0e,$8d,$0e,$83,$1e
	.byte $87,$0e,$85
	.byte $ff,$13
	.word @ref16
	.byte $ff,$13
	.word @ref16
@ref19:
	.byte $87,$80,$0c,$83,$82,$0c,$87,$0e,$8d,$0e,$8d,$0e,$8b,$0e,$0e,$8d
	.byte $0e,$8b,$0e,$85,$80,$1c,$20,$04,$0a,$0a,$0e,$14,$18,$1c
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref20:
	.byte $32,$85,$35,$32,$85,$33,$34,$89,$33,$35,$35,$34,$34,$38,$38,$35
	.byte $32,$85,$33,$34,$8d,$35,$35,$32,$83,$34,$34,$34,$33,$33,$33,$35
	.byte $32,$81
	.byte $ff,$22
	.word @ref20
@ref22:
	.byte $32,$8d,$32,$8d,$32,$8d,$32,$8d,$32,$8d,$32,$8d,$32,$85,$32,$85
	.byte $33,$33,$32,$32,$32,$32
@ref23:
	.byte $33,$33,$36,$34,$36,$34,$32,$85,$34,$34,$34,$34,$34,$83,$34,$34
	.byte $36,$38,$d1
@ref24:
	.byte $32,$95,$34,$8d,$38,$87,$1e,$1c,$34,$34,$34,$8b,$33,$32,$32,$35
	.byte $33,$35,$35,$33,$32,$32,$34,$85,$34,$85,$34,$34,$34,$34
	.byte $fd
	.word @song0ch4loop
